2021-07-26 21:37:01,901, ERROR, root, Бот упал с ошибкой: list index out of range
Traceback (most recent call last):
  File "/mnt/c/Dev/api_sp1_bot-1/homework.py", line 104, in main
    homework = homeworks['homeworks'][0]
IndexError: list index out of range
2021-07-26 21:37:01,913, INFO, root, Бот отправил сообщение Бот упал с ошибкой: list index out of range
2021-07-26 21:37:07,563, ERROR, root, Бот упал с ошибкой: list index out of range
Traceback (most recent call last):
  File "/mnt/c/Dev/api_sp1_bot-1/homework.py", line 104, in main
    homework = homeworks['homeworks'][0]
IndexError: list index out of range
2021-07-26 21:37:07,569, INFO, root, Бот отправил сообщение Бот упал с ошибкой: list index out of range
