2021-07-27 02:46:53,171, INFO, root, Бот отправил сообщение Новой домашки нет
2021-07-28 18:21:23,353, ERROR, Бот упал с ошибкой: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/mnt/c/Dev/api_sp1_bot-1/homework.py", line 110, in main
    homework = homeworks_list.get(0)
AttributeError: 'list' object has no attribute 'get'
2021-07-28 18:21:28,938, ERROR, Бот упал с ошибкой: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/mnt/c/Dev/api_sp1_bot-1/homework.py", line 110, in main
    homework = homeworks_list.get(0)
AttributeError: 'list' object has no attribute 'get'
2021-07-28 18:21:34,288, ERROR, Бот упал с ошибкой: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/mnt/c/Dev/api_sp1_bot-1/homework.py", line 110, in main
    homework = homeworks_list.get(0)
AttributeError: 'list' object has no attribute 'get'
